# Generated by Django 4.1.1 on 2022-10-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['create_time']},
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='images/default_pic.png', null=True, upload_to='images/'),
        ),
    ]
