# Generated by Django 4.1.1 on 2022-09-19 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_file_authors_file_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='paddocks',
        ),
        migrations.RemoveField(
            model_name='file',
            name='tags',
        ),
        migrations.AddField(
            model_name='file',
            name='paddocks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.paddock'),
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.tag'),
        ),
    ]
