# Generated by Django 4.1.1 on 2022-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
