# Generated by Django 4.1.1 on 2022-10-05 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_alter_paddock_options_alter_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='year',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2007), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
