# Generated by Django 4.1.1 on 2022-10-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_file_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.PositiveIntegerField(default=2022),
        ),
    ]
